'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'fr' | 'ar';

interface LanguageContextType {
  language: Language;
  locale: Language;
  setLanguage: (lang: Language) => void;
  setLocale: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation & Header
    catalog: 'Catalog',
    dtfPrints: 'DTF Prints',
    lookbook: 'Lookbook',
    trackOrder: 'Track Order',
    contact: 'Contact',
    signIn: 'Sign In',
    account: 'Account',
    search: 'Search',
    searchPlaceholder: 'Search the store…',

    // Cart & Checkout
    cart: 'Your Bag',
    emptyCart: 'Your bag is empty',
    subtotal: 'Subtotal',
    shipping: 'Shipping',
    total: 'Total',
    free: 'FREE',
    remove: 'Remove',
    addToCart: 'Add to Bag',
    added: 'Added ✓',
    checkout: 'Checkout',
    continueShopping: 'Continue Shopping',
    checkoutTitle: 'Bank Transfer Payment',
    contactInfo: 'Contact Information',
    shippingAddress: 'Shipping Address',
    confirmOrder: 'Confirm Order',
    processing: 'Processing...',
    orderSummary: 'Order Summary',
    totalToPay: 'Total Amount',
    returnToStore: 'Return to Store',
    bankDetailsTitle: 'CIH BANK DETAILS',
    orderRecorded: 'Order Placed!',
    transferNotice: 'Perform the bank transfer to our CIH account below to confirm shipment.',
    accountHolder: 'Account Holder',
    transferReason: 'Transfer Reference / Reason',
    viewInAccount: 'View Order in My Account',

    // Product & Catalog Categories
    selectSize: 'Select Size',
    size: 'Size',
    color: 'Color',
    quantity: 'Qty',
    viewDetails: 'Details',
    quickAdd: 'Quick Add',
    newDrop: 'New Drop',
    allItems: 'All Items',
    streetwear: 'Streetwear',
    accessories: 'Accessories',
    apparel: 'Apparel',
    hoodies: 'Hoodies',
    tees: 'Tees',
    tops: 'Tops',
    bottoms: 'Bottoms',
    featured: 'Featured',
    newest: 'Newest',
    lowToHigh: 'Price: Low to High',
    highToLow: 'Price: High to Low',
    resetFilters: 'Reset Filters',
    clear: 'Clear',
    apply: 'Apply',
    save: 'Save',
    itemsFound: 'Items Found',
    outOfStock: 'Out Of Stock',
    inStock: 'In Stock',
    outOfStockBadge: 'Sold Out',
    loadingProduct: 'Loading product…',

    // Customer Forms & Details
    firstName: 'First Name',
    lastName: 'Last Name',
    fullName: 'Full Name *',
    email: 'Email Address *',
    phone: 'Phone Number (e.g. 0661234567)',
    address: 'Address',
    addressLine1: 'Address Line 1',
    addressLine2: 'Address Line 2 (Optional)',
    fullAddress: 'Full Address (Neighborhood, Street, No.)',
    city: 'City',
    postalCode: 'Postal Code',
    country: 'Country',
    note: 'Order Notes (Optional)',
    createAccount: 'Create an Account (Optional)',
    password: 'Password',
    saveAddress: 'Save Address',
    passwordHint: 'Leave blank to order as guest',

    // Orders & Status
    pendingPayment: 'Awaiting Payment',
    pendingConfirmation: 'Payment Confirmed',
    shipped: 'Shipped',
    delivered: 'Delivered',
    canceled: 'Canceled',
    orderPlaced: 'Order Confirmed',
    orderNumber: 'Order #',
    bankDetails: 'Bank Transfer',
    transferToAccount: 'Transfer to our account below',
    rib: 'RIB',
    reference: 'Transfer Reference',
    required: 'Required',
    mandatory: 'Mandatory',
    whatsappProof: 'Send proof on WhatsApp',
    myAccount: 'My Account',
    orders: 'Orders',
    profile: 'Address & Info',
    addressSaved: 'Address updated',
    saveError: 'Unable to save changes',
    noOrders: 'No orders yet',
    viewCatalog: 'Shop Now',
    orderNo: 'Order',
    itemsOrdered: 'Items Ordered',
    deliveryAddress: 'Delivery Address',
    defaultAddress: 'Default Address',
    transferOf: 'Transfer of',
    loading: 'Loading…',

    // Value Props & Footer
    freeShipping: 'Free Shipping',
    freeShippingOn: 'on orders over 500 MAD',
    returns: 'Easy Returns',
    returnsPolicy: 'within 14 days',
    ecoPackaging: 'Eco Packaging',
    ecoDetails: 'recycled & reusable',
    securePayment: 'Secure Transfer',
    secureDetails: 'bank-level encryption',
    curatedCollections: 'Curated Collections',
    shopByCategory: 'Shop by Category',
    outerwear: 'Outerwear',
    essentials: 'Everyday Essentials',
    piecesLimited: 'PIECES — LIMITED',
    subscribe: 'Subscribe',
    subscribed: 'Subscribed ✓ Welcome',
    subscribeStudio: 'Join the studio',
    subscribeText: 'New drops, archive sales, early access.',
    back: 'Back',
    mandatoryFields: 'All mandatory fields',
    continue: 'Continue',

    // Contact Page
    customerSupport: 'Customer Support',
    contactTitle: 'Get in Touch',
    contactSubtitle: 'Have questions about your order, shipping policies, or sizing? Our support team responds within 24 hours.',
    directContact: 'Direct Contact',
    whatsappSupport: 'WhatsApp Support',
    emailAddress: 'Email Address',
    workingHours: 'Working Hours',
    workingHoursVal: 'Mon - Sat (09:00 - 19:00 GMT+1)',
    policiesTitle: 'Shipping & Return Policies',
    policiesBody: 'Orders ship nationwide via Amana Colis Postaux (24-48 hours delivery). Returns are accepted within 7 days of delivery for unworn items with tags attached.',
    sendMessage: 'Send A Message',
    subject: 'Subject',
    yourMessage: 'Your Message *',
    messagePlaceholder: 'Describe your inquiry or include your order reference number…',
    msgDelivered: 'Message Delivered!',
    msgThankYou: 'Thank you for reaching out. We have logged your request and will send a reply shortly.',
    sendAnother: 'Send another message',
    contactSend: 'Send Message',

    // Track Order Page
    shipmentStatus: 'Shipment Status',
    trackOrderTitle: 'Track Your Order',
    trackOrderSubtitle: 'Enter your Order ID or Email address to view real-time shipment status and tracking details.',
    trackInputPlaceholder: 'Enter Order ID or Email…',
    trackBtn: 'Track Order',
    noOrdersFound: 'No orders found matching',
    placedOn: 'Placed on',
    totalPaid: 'Total Paid',

    // Auth & Error Messages
    loginTitle: 'Welcome Back',
    loginSubtitle: 'Sign in to view orders & checkout faster.',
    loginWith: 'Sign in with Email',
    orRegister: 'Or create an account',
    forgot: 'Forgot password',
    newCustomer: 'New to ZYN?',
    createAccountCTA: 'Create Account',
    haveAccount: 'Already have an account?',
    registerHere: 'Register Here',
    signOut: 'Sign Out',
    requiredField: 'Please complete this field',
    errorAddress: 'Please fill address and city',
    errorContact: 'Please complete contact info',
    errorEmptyCart: 'Your bag is empty',
    errorSubmit: 'Something went wrong — please try again',
  },
  fr: {
    // Navigation & Header
    catalog: 'Catalogue',
    dtfPrints: 'Impressions DTF',
    lookbook: 'Lookbook',
    trackOrder: 'Suivre Commande',
    contact: 'Contact',
    signIn: 'Connexion',
    account: 'Compte',
    search: 'Recherche',
    searchPlaceholder: 'Rechercher dans le store…',

    // Cart & Checkout
    cart: 'Votre Panier',
    emptyCart: 'Votre panier est vide',
    subtotal: 'Sous-total',
    shipping: 'Livraison',
    total: 'Total',
    free: 'OFFERT',
    remove: 'Supprimer',
    addToCart: 'Ajouter au Panier',
    added: 'Ajouté ✓',
    checkout: 'Commander',
    continueShopping: 'Continuer mes achats',
    checkoutTitle: 'Paiement Par Virement Bancaire',
    contactInfo: 'Informations de Contact',
    shippingAddress: 'Adresse de Livraison',
    confirmOrder: 'Confirmer la commande',
    processing: 'Traitement en cours...',
    orderSummary: 'Récapitulatif',
    totalToPay: 'Total à Payer',
    returnToStore: 'Retour au Store',
    bankDetailsTitle: 'COORDONNÉES CIH BANK',
    orderRecorded: 'Commande Enregistrée !',
    transferNotice: 'Effectuez le virement bancaire sur notre compte CIH ci-dessous pour valider l\'expédition.',
    accountHolder: 'Titulaire du compte',
    transferReason: 'Motif du Virement',
    viewInAccount: 'Voir ma commande dans l\'Espace Client',

    // Product & Catalog Categories
    selectSize: 'Choisir une Taille',
    size: 'Taille',
    color: 'Couleur',
    quantity: 'Qté',
    viewDetails: 'Détails',
    quickAdd: 'Ajout Rapide',
    newDrop: 'Nouveauté',
    allItems: 'Tous les Articles',
    streetwear: 'Streetwear',
    accessories: 'Accessoires',
    apparel: 'Vêtements',
    hoodies: 'Hoodies',
    tees: 'T-Shirts',
    tops: 'Hauts',
    bottoms: 'Bas',
    featured: 'En Vedette',
    newest: 'Plus Récents',
    lowToHigh: 'Prix ↑',
    highToLow: 'Prix ↓',
    resetFilters: 'Réinitialiser',
    clear: 'Effacer',
    apply: 'Appliquer',
    save: 'Enregistrer',
    itemsFound: 'Articles Trouvés',
    outOfStock: 'Rupture de Stock',
    inStock: 'En Stock',
    outOfStockBadge: 'Rupture',
    loadingProduct: 'Chargement du produit…',

    // Customer Forms & Details
    firstName: 'Prénom',
    lastName: 'Nom',
    fullName: 'Nom Complet *',
    email: 'Adresse Email *',
    phone: 'Téléphone (ex: 0661234567)',
    address: 'Adresse',
    addressLine1: 'Adresse Ligne 1',
    addressLine2: 'Adresse Ligne 2 (Optionnel)',
    fullAddress: 'Adresse complète (Quartier, Rue, N°)',
    city: 'Ville',
    postalCode: 'Code Postal',
    country: 'Pays',
    note: 'Remarques (Optionnel)',
    createAccount: 'Créer un Compte (Optionnel)',
    password: 'Mot de passe',
    saveAddress: 'Sauvegarder l\'Adresse',
    passwordHint: 'Laisser vide pour commander en invité',

    // Orders & Status
    pendingPayment: 'Virement Attendu',
    pendingConfirmation: 'Paiement Vérifié',
    shipped: 'Expédié',
    delivered: 'Livré',
    canceled: 'Annulé',
    orderPlaced: 'Commande Enregistrée',
    orderNumber: 'Commande N°',
    bankDetails: 'Virement Bancaire',
    transferToAccount: 'Effectuez le virement sur notre compte ci-dessous',
    rib: 'RIB',
    reference: 'Motif du Virement',
    required: 'Requis',
    mandatory: 'Obligatoire',
    whatsappProof: 'Envoyer une preuve sur WhatsApp',
    myAccount: 'Espace Client',
    orders: 'Mes Commandes',
    profile: 'Mon Adresse',
    addressSaved: 'Adresse mise à jour',
    saveError: 'Impossible d\'enregistrer',
    noOrders: 'Aucune commande',
    viewCatalog: 'Commencer les Achats',
    orderNo: 'Commande',
    itemsOrdered: 'Articles Commandés',
    deliveryAddress: 'Adresse de Livraison',
    defaultAddress: 'Adresse par Défaut',
    transferOf: 'Effectuez le virement de',
    loading: 'Chargement…',

    // Value Props & Footer
    freeShipping: 'Livraison Offerte',
    freeShippingOn: 'dès 500 MAD',
    returns: 'Retours Faciles',
    returnsPolicy: 'sous 14 jours',
    ecoPackaging: 'Emballage Éco',
    ecoDetails: 'recyclé & réutilisable',
    securePayment: 'Virement Sécurisé',
    secureDetails: 'chiffrement banque',
    curatedCollections: 'Collections',
    shopByCategory: 'Catégories',
    outerwear: 'Manteaux & Vestes',
    essentials: 'Essentiels du Quotidien',
    piecesLimited: 'MODÈLES — LIMITÉS',
    subscribe: 'S\'inscrire',
    subscribed: 'Inscrit ✓ Bienvenue',
    subscribeStudio: 'Rejoindre le studio',
    subscribeText: 'Nouveautés, soldes, accès anticipé.',
    back: 'Retour',
    mandatoryFields: 'Veuillez remplir tous les champs obligatoires',
    continue: 'Continuer',

    // Contact Page
    customerSupport: 'Support Client',
    contactTitle: 'Nous Contacter',
    contactSubtitle: 'Des questions sur votre commande, nos livraisons ou les tailles ? Notre équipe vous répond sous 24h.',
    directContact: 'Contact Direct',
    whatsappSupport: 'Support WhatsApp',
    emailAddress: 'Adresse Email',
    workingHours: 'Heures d\'Ouverture',
    workingHoursVal: 'Lun - Sam (09:00 - 19:00 GMT+1)',
    policiesTitle: 'Livraison & Retours',
    policiesBody: 'Livraison partout au Maroc via Amana Colis Postaux (24-48h). Retours acceptés sous 7 jours pour les articles non portés avec étiquette.',
    sendMessage: 'Envoyer un Message',
    subject: 'Sujet',
    yourMessage: 'Votre Message *',
    messagePlaceholder: 'Décrivez votre demande ou incluez votre numéro de commande…',
    msgDelivered: 'Message Envoyé !',
    msgThankYou: 'Merci de nous avoir contactés. Nous vous répondrons très rapidement.',
    sendAnother: 'Envoyer un autre message',
    contactSend: 'Envoyer le message',

    // Track Order Page
    shipmentStatus: 'Statut du Colis',
    trackOrderTitle: 'Suivre ma Commande',
    trackOrderSubtitle: 'Entrez votre N° de commande ou Email pour consulter l\'état d\'avancement de votre livraison.',
    trackInputPlaceholder: 'N° de commande ou Email…',
    trackBtn: 'Suivre',
    noOrdersFound: 'Aucune commande trouvée pour',
    placedOn: 'Passée le',
    totalPaid: 'Total Payé',

    // Auth & Error Messages
    loginTitle: 'Bienvenue',
    loginSubtitle: 'Connectez-vous pour suivre vos commandes.',
    loginWith: 'Se connecter par email',
    orRegister: 'Ou créer un compte',
    forgot: 'Mot de passe oublié',
    newCustomer: 'Nouveau sur ZYN ?',
    createAccountCTA: 'Créer un Compte',
    haveAccount: 'Déjà un compte ?',
    registerHere: 'S\'inscrire',
    signOut: 'Déconnexion',
    requiredField: 'Veuillez remplir ce champ',
    errorAddress: 'Renseignez adresse et ville',
    errorContact: 'Renseignez vos coordonnées',
    errorEmptyCart: 'Votre panier est vide',
    errorSubmit: 'Erreur — merci de réessayer',
  },
  ar: {
    // Navigation & Header
    catalog: 'الكتالوج',
    dtfPrints: 'طباعة DTF',
    lookbook: 'كتليب الصور',
    trackOrder: 'تتبع الطلب',
    contact: 'اتصل بنا',
    signIn: 'تسجيل الدخول',
    account: 'الحساب',
    search: 'بحث',
    searchPlaceholder: 'ابحث في المتجر…',

    // Cart & Checkout
    cart: 'سلة التسوق',
    emptyCart: 'سلتك فارغة',
    subtotal: 'المجموع الفرعي',
    shipping: 'الشحن',
    total: 'المجموع',
    free: 'مجاني',
    remove: 'حذف',
    addToCart: 'أضف إلى السلة',
    added: 'تمت الإضافة ✓',
    checkout: 'إتمام الطلب',
    continueShopping: 'مواصلة التسوق',
    checkoutTitle: 'الدفع عبر التحويل البنكي',
    contactInfo: 'معلومات الاتصال',
    shippingAddress: 'عنوان الشحن',
    confirmOrder: 'تأكيد الطلب',
    processing: 'جاري المعالجة...',
    orderSummary: 'ملخص الطلب',
    totalToPay: 'المبلغ الإجمالي',
    returnToStore: 'العودة للمتجر',
    bankDetailsTitle: 'معلومات حساب CIH BANK',
    orderRecorded: 'تم تسجيل طلبك بنجاح!',
    transferNotice: 'يرجى إجراء التحويل البنكي إلى حسابنا أدناه لتأكيد شحن طلبك.',
    accountHolder: 'صاحب الحساب',
    transferReason: 'سبب التحويل / رقم الطلب',
    viewInAccount: 'عرض الطلب في حسابي',

    // Product & Catalog Categories
    selectSize: 'اختر المقاس',
    size: 'المقاس',
    color: 'اللون',
    quantity: 'الكمية',
    viewDetails: 'التفاصيل',
    quickAdd: 'إضافة سريعة',
    newDrop: 'جديد المتجر',
    allItems: 'كل المنتجات',
    streetwear: 'ملابس الشارع',
    accessories: 'إكسسوارات',
    apparel: 'ملابس',
    hoodies: 'هوديز',
    tees: 'تيشرتات',
    tops: 'ملابس علوية',
    bottoms: 'ملابس سفلية',
    featured: 'مميز',
    newest: 'الأحدث',
    lowToHigh: 'السعر: تصاعدياً',
    highToLow: 'السعر: تنازلياً',
    resetFilters: 'مسح الفلاتر',
    clear: 'مسح',
    apply: 'تطبيق',
    save: 'حفظ',
    itemsFound: 'منتجات متوفرة',
    outOfStock: 'نفذت الكمية',
    inStock: 'متوفر',
    outOfStockBadge: 'نفذ',
    loadingProduct: 'جاري تحميل المنتج…',

    // Customer Forms & Details
    firstName: 'الاسم الأول',
    lastName: 'النسب',
    fullName: 'الاسم الكامل *',
    email: 'البريد الإلكتروني *',
    phone: 'رقم الهاتف (مثال: 0661234567)',
    address: 'العنوان',
    addressLine1: 'العنوان - السطر الأول',
    addressLine2: 'العنوان - السطر الثاني (اختياري)',
    fullAddress: 'العنوان الكامل (الحي، الشارع، الرقم)',
    city: 'المدينة',
    postalCode: 'الرمز البريدي',
    country: 'الدولة',
    note: 'ملاحظات (اختياري)',
    createAccount: 'إنشاء حساب (اختياري)',
    password: 'كلمة المرور',
    saveAddress: 'حفظ العنوان',
    passwordHint: 'اتركه فارغاً للطلب كضيف',

    // Orders & Status
    pendingPayment: 'في انتظار التحويل',
    pendingConfirmation: 'تأكيد الاستلام',
    shipped: 'تم الشحن',
    delivered: 'تم التوصيل',
    canceled: 'ملغي',
    orderPlaced: 'تم تسجيل طلبك',
    orderNumber: 'رقم الطلب',
    bankDetails: 'التحويل البنكي',
    transferToAccount: 'يرجى التحويل إلى حسابنا أدناه',
    rib: 'RIB',
    reference: 'سبب التحويل',
    required: 'مطلوب',
    mandatory: 'إلزامي',
    whatsappProof: 'أرسل الإثبات عبر واتساب',
    myAccount: 'حسابي',
    orders: 'طلباتي',
    profile: 'عنواني ومعلوماتي',
    addressSaved: 'تم تحديث العنوان',
    saveError: 'تعذر الحفظ',
    noOrders: 'لا توجد طلبات بعد',
    viewCatalog: 'ابدأ التسوق',
    orderNo: 'طلب',
    itemsOrdered: 'المنتجات المطلوبة',
    deliveryAddress: 'عنوان التوصيل',
    defaultAddress: 'العنوان الافتراضي',
    transferOf: 'يرجى التحويل بمبلغ',
    loading: 'جاري التحميل…',

    // Value Props & Footer
    freeShipping: 'شحن مجاني',
    freeShippingOn: 'للطلبات فوق 500 درهم',
    returns: 'إرجاع سهل',
    returnsPolicy: 'خلال 14 يوماً',
    ecoPackaging: 'تغليف بيئي',
    ecoDetails: 'معاد تدويره',
    securePayment: 'تحويل آمن',
    secureDetails: 'تشفير بنكي',
    curatedCollections: 'تشكيلات مختارة',
    shopByCategory: 'تسوق حسب الفئة',
    outerwear: 'الملابس الخارجية',
    essentials: 'الأساسيات اليومية',
    piecesLimited: 'قطع محدودة',
    subscribe: 'اشترك',
    subscribed: 'تم الاشتراك ✓ أهلاً بك',
    subscribeStudio: 'انضم للأستوديو',
    subscribeText: 'الجديد والعروض والوصول المبكر.',
    back: 'رجوع',
    mandatoryFields: 'يرجى تعبئة الحقول الإلزامية',
    continue: 'متابعة',

    // Contact Page
    customerSupport: 'دعم العملاء',
    contactTitle: 'تواصل معنا',
    contactSubtitle: 'أسئلة حول طلبك أو الشحن أو المقاسات؟ فريقنا يجيب خلال 24 ساعة.',
    directContact: 'اتصال مباشر',
    whatsappSupport: 'دعم واتساب',
    emailAddress: 'البريد الإلكتروني',
    workingHours: 'أوقات العمل',
    workingHoursVal: 'الإثنين - السبت (09:00 - 19:00 GMT+1)',
    policiesTitle: 'سياسة الشحن والإرجاع',
    policiesBody: 'التوصيل لجميع المدن عبر أمانة (24-48 ساعة). الإرجاع مقبول خلال 7 أيام للمنتجات غير المستعملة.',
    sendMessage: 'إرسال رسالة',
    subject: 'الموضوع',
    yourMessage: 'رسالتك *',
    messagePlaceholder: 'اكتب تفاصيل استفسارك أو رقم الطلب…',
    msgDelivered: 'تم إرسال الرسالة!',
    msgThankYou: 'شكراً لتواصلك معنا. سنقوم بالرد عليك في أقرب وقت.',
    sendAnother: 'إرسال رسالة أخرى',
    contactSend: 'إرسال الرسالة',

    // Track Order Page
    shipmentStatus: 'حالة الشحنة',
    trackOrderTitle: 'تتبع طلبك',
    trackOrderSubtitle: 'أدخل رقم الطلب أو البريد الإلكتروني لمتابعة حالة الشحنة.',
    trackInputPlaceholder: 'رقم الطلب أو البريد الإلكتروني…',
    trackBtn: 'تتبع الطلب',
    noOrdersFound: 'لم يتم العثور على طلبات مطابقة لـ',
    placedOn: 'تاريخ الطلب',
    totalPaid: 'المبلغ المدفوع',

    // Auth & Error Messages
    loginTitle: 'مرحباً بك',
    loginSubtitle: 'سجل الدخول لمتابعة طلباتك.',
    loginWith: 'تسجيل الدخول بالبريد',
    orRegister: 'أو أنشئ حساباً',
    forgot: 'نسيت كلمة المرور',
    newCustomer: 'جديد على ZYN ؟',
    createAccountCTA: 'إنشاء حساب',
    haveAccount: 'لديك حساب بالفعل؟',
    registerHere: 'سجل هنا',
    signOut: 'تسجيل الخروج',
    requiredField: 'يرجى تعبئة هذا الحقل',
    errorAddress: 'يرجى إدخال العنوان والمدينة',
    errorContact: 'يرجى تعبئة معلومات الاتصال',
    errorEmptyCart: 'سلتك فارغة',
    errorSubmit: 'حصل خطأ — يرجى المحاولة مجدداً',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    const savedLang = localStorage.getItem('zyn_lang') as Language;
    if (savedLang && ['en', 'fr', 'ar'].includes(savedLang)) {
      setLanguageState(savedLang);
      document.documentElement.dir = savedLang === 'ar' ? 'rtl' : 'ltr';
      document.documentElement.lang = savedLang;
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('zyn_lang', lang);
    if (typeof document !== 'undefined') {
      document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
      document.documentElement.lang = lang;
    }
  };

  const t = (key: string) => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  const isRTL = language === 'ar';

  return (
    <LanguageContext.Provider
      value={{
        language,
        locale: language,
        setLanguage,
        setLocale: setLanguage,
        t,
        isRTL,
      }}
    >
      <div dir={isRTL ? 'rtl' : 'ltr'}>{children}</div>
    </LanguageContext.Provider>
  );
}

// Aliases so both import styles work across any file
export const IntlProvider = LanguageProvider;
export default LanguageProvider;

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

export const useTranslation = useLanguage;