'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'fr' | 'ar';

interface LanguageContextType {
  language: Language;
  locale: Language;
  setLanguage: (lang: Language) => void;
  setLocale: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    catalog: 'Catalog',
    dtfPrints: 'DTF Prints',
    lookbook: 'Lookbook',
    trackOrder: 'Track Order',
    contact: 'Contact',
    signIn: 'Sign In',
    account: 'Account',
    search: 'Search',
    searchPlaceholder: 'Search the store…',
    addToCart: 'Add to Bag',
    added: 'Added',
    checkout: 'Checkout',
    continueShopping: 'Continue Shopping',
    subscribe: 'Subscribe',
    subscribed: 'Subscribed ✓ Welcome',
    selectSize: 'Select Size',
    size: 'Size',
    color: 'Color',
    quantity: 'Qty',
    viewDetails: 'View Details',
    quickAdd: 'Quick Add',
    newDrop: 'New Drop',
    allItems: 'All Items',
    featured: 'Featured',
    newest: 'Newest',
    lowToHigh: 'Price: Low to High',
    highToLow: 'Price: High to Low',
    resetFilters: 'Reset Filters',
    clear: 'Clear',
    apply: 'Apply',
    save: 'Save',
    signOut: 'Sign Out',
    cart: 'Your Bag',
    emptyCart: 'Your bag is empty',
    subtotal: 'Subtotal',
    shipping: 'Shipping',
    total: 'Total',
    free: 'FREE',
    remove: 'Remove',
    itemsFound: 'Items Found',
    orderSummary: 'Summary',
    delivery: 'Delivery',
    payment: 'Payment',
    totalToPay: 'Total to Pay',
    firstName: 'First Name',
    lastName: 'Last Name',
    fullName: 'Full Name',
    email: 'Email',
    phone: 'Phone',
    address: 'Address',
    addressLine1: 'Address Line 1',
    addressLine2: 'Address Line 2 (Optional)',
    city: 'City',
    postalCode: 'Postal Code',
    country: 'Country',
    note: 'Order Notes (Optional)',
    createAccount: 'Create an Account (Optional)',
    password: 'Password',
    saveAddress: 'Save Address',
    passwordHint: 'Leave blank to order as guest',
    pendingPayment: 'Awaiting Payment',
    pendingConfirmation: 'Payment Confirmed',
    processing: 'Processing',
    shipped: 'Shipped',
    delivered: 'Delivered',
    canceled: 'Canceled',
    orderPlaced: 'Order Confirmed',
    orderNumber: 'Order #',
    bankDetails: 'Bank Transfer',
    transferToAccount: 'Transfer to our account below',
    accountHolder: 'Account Holder',
    rib: 'RIB',
    reference: 'Transfer Reference',
    required: 'Required',
    mandatory: 'Mandatory',
    whatsappProof: 'Send proof on WhatsApp',
    viewInAccount: 'View in My Account',
    outOfStock: 'Item out of stock',
    myAccount: 'My Account',
    orders: 'Orders',
    profile: 'Address & Info',
    addressSaved: 'Address updated',
    saveError: 'Unable to save changes',
    noOrders: 'No orders yet',
    viewCatalog: 'Shop Now',
    orderNo: 'Order',
    itemsOrdered: 'Items Ordered',
    deliveryAddress: 'Delivery Address',
    defaultAddress: 'Default Address',
    transferOf: 'Transfer of',
    loading: 'Loading…',
    freeShipping: 'Free Shipping',
    freeShippingOn: 'on orders over 500 MAD',
    returns: 'Easy Returns',
    returnsPolicy: 'within 14 days',
    ecoPackaging: 'Eco Packaging',
    ecoDetails: 'recycled & reusable',
    securePayment: 'Secure Transfer',
    secureDetails: 'bank-level encryption',
    curatedCollections: 'Curated Collections',
    shopByCategory: 'Shop by Category',
    outerwear: 'Outerwear',
    essentials: 'Everyday Essentials',
    streetwear: 'Streetwear',
    piecesLimited: 'PIECES — LIMITED',
    subscribeStudio: 'Join the studio',
    subscribeText: 'New drops, archive sales, early access.',
    back: 'Back',
    returnToStore: 'Back to Store',
    loadingProduct: 'Loading product…',
    outOfStockBadge: 'Sold Out',
    mandatoryFields: 'All mandatory fields',
    continue: 'Continue',
    contactTitle: 'Get in Touch',
    contactSubtitle: 'Questions, collabs, orders — we reply fast.',
    contactFormEmail: 'Your email',
    contactFormMessage: 'Your message',
    contactSend: 'Send Message',
    loginTitle: 'Welcome Back',
    loginSubtitle: 'Sign in to view orders & checkout faster.',
    loginWith: 'Sign in with Email',
    orRegister: 'Or create an account',
    forgot: 'Forgot password',
    newCustomer: 'New to ZYN?',
    createAccountCTA: 'Create Account',
    haveAccount: 'Already have an account?',
    registerHere: 'Register Here',
    requiredField: 'Please complete this field',
    errorAddress: 'Please fill address and city',
    errorContact: 'Please complete contact info',
    errorEmptyCart: 'Your bag is empty',
    errorSubmit: 'Something went wrong — please try again',
  },
  fr: {
    catalog: 'Catalogue',
    dtfPrints: 'Impressions DTF',
    lookbook: 'Lookbook',
    trackOrder: 'Suivi Commande',
    contact: 'Contact',
    signIn: 'Connexion',
    account: 'Compte',
    search: 'Recherche',
    searchPlaceholder: 'Rechercher dans le store…',
    addToCart: 'Ajouter au Panier',
    added: 'Ajouté ✓',
    checkout: 'Commander',
    continueShopping: 'Continuer mes achats',
    subscribe: 'S\'inscrire',
    subscribed: 'Inscrit ✓ Bienvenue',
    selectSize: 'Choisir une Taille',
    size: 'Taille',
    color: 'Couleur',
    quantity: 'Qté',
    viewDetails: 'Voir le Produit',
    quickAdd: 'Ajout Rapide',
    newDrop: 'Nouveauté',
    allItems: 'Tous les Articles',
    featured: 'En Vedette',
    newest: 'Plus Récents',
    lowToHigh: 'Prix ↑',
    highToLow: 'Prix ↓',
    resetFilters: 'Réinitialiser',
    clear: 'Effacer',
    apply: 'Appliquer',
    save: 'Enregistrer',
    signOut: 'Déconnexion',
    cart: 'Votre Panier',
    emptyCart: 'Votre panier est vide',
    subtotal: 'Sous-total',
    shipping: 'Livraison',
    total: 'Total',
    free: 'OFFERT',
    remove: 'Supprimer',
    itemsFound: 'Articles Trouvés',
    orderSummary: 'Récapitulatif',
    delivery: 'Mode de Livraison',
    payment: 'Paiement',
    totalToPay: 'Total à Payer',
    firstName: 'Prénom',
    lastName: 'Nom',
    fullName: 'Nom Complet',
    email: 'Email',
    phone: 'Téléphone',
    address: 'Adresse',
    addressLine1: 'Adresse Ligne 1',
    addressLine2: 'Adresse Ligne 2 (Optionnel)',
    city: 'Ville',
    postalCode: 'Code Postal',
    country: 'Pays',
    note: 'Remarques (Optionnel)',
    createAccount: 'Créer un Compte (Optionnel)',
    password: 'Mot de passe',
    saveAddress: 'Sauvegarder l\'Adresse',
    passwordHint: 'Laisser vide pour commander en invité',
    pendingPayment: 'Virement Attendu',
    pendingConfirmation: 'Paiement Vérifié',
    processing: 'En Préparation',
    shipped: 'Expédié',
    delivered: 'Livré',
    canceled: 'Annulé',
    orderPlaced: 'Commande Enregistrée',
    orderNumber: 'Commande N°',
    bankDetails: 'Virement Bancaire',
    transferToAccount: 'Effectuez le virement sur notre compte ci-dessous',
    accountHolder: 'Titulaire du Compte',
    rib: 'RIB',
    reference: 'Motif du Virement',
    required: 'Requis',
    mandatory: 'Obligatoire',
    whatsappProof: 'Envoyer une preuve sur WhatsApp',
    viewInAccount: 'Voir dans Mon Compte',
    outOfStock: 'Article en rupture',
    myAccount: 'Espace Client',
    orders: 'Mes Commandes',
    profile: 'Mon Adresse',
    addressSaved: 'Adresse mise à jour',
    saveError: 'Impossible d\'enregistrer',
    noOrders: 'Aucune commande',
    viewCatalog: 'Commencer les Achats',
    orderNo: 'Commande',
    itemsOrdered: 'Articles Commandés',
    deliveryAddress: 'Adresse de Livraison',
    defaultAddress: 'Adresse par Défaut',
    transferOf: 'Effectuez le virement de',
    loading: 'Chargement…',
    freeShipping: 'Livraison Offerte',
    freeShippingOn: 'dès 500 MAD',
    returns: 'Retours Faciles',
    returnsPolicy: 'sous 14 jours',
    ecoPackaging: 'Emballage Éco',
    ecoDetails: 'recyclé & réutilisable',
    securePayment: 'Virement Sécurisé',
    secureDetails: 'chiffrement banque',
    curatedCollections: 'Collections',
    shopByCategory: 'Catégories',
    outerwear: 'Manteaux & Vestes',
    essentials: 'Essentiels du Quotidien',
    streetwear: 'Streetwear',
    piecesLimited: 'MODÈLES — LIMITÉS',
    subscribeStudio: 'Rejoindre le studio',
    subscribeText: 'Nouveautés, soldes, accès anticipé.',
    back: 'Retour',
    returnToStore: 'Retour au Store',
    loadingProduct: 'Chargement du produit…',
    outOfStockBadge: 'Rupture',
    mandatoryFields: 'Veuillez remplir tous les champs obligatoires',
    continue: 'Continuer',
    contactTitle: 'Nous Contacter',
    contactSubtitle: 'Questions, collabs, commandes — on vous répond vite.',
    contactFormEmail: 'Votre email',
    contactFormMessage: 'Votre message',
    contactSend: 'Envoyer',
    loginTitle: 'Bienvenue',
    loginSubtitle: 'Connectez-vous pour suivre vos commandes.',
    loginWith: 'Se connecter par email',
    orRegister: 'Ou créer un compte',
    forgot: 'Mot de passe oublié',
    newCustomer: 'Nouveau sur ZYN ?',
    createAccountCTA: 'Créer un Compte',
    haveAccount: 'Déjà un compte ?',
    registerHere: 'S\'inscrire',
    requiredField: 'Veuillez remplir ce champ',
    errorAddress: 'Renseignez adresse et ville',
    errorContact: 'Renseignez vos coordonnées',
    errorEmptyCart: 'Votre panier est vide',
    errorSubmit: 'Erreur — merci de réessayer',
  },
  ar: {
    catalog: 'الكتالوج',
    dtfPrints: 'طباعة DTF',
    lookbook: 'كتليب الشتاء',
    trackOrder: 'تتبع الطلب',
    contact: 'اتصل بنا',
    signIn: 'تسجيل الدخول',
    account: 'الحساب',
    search: 'بحث',
    searchPlaceholder: 'ابحث في المتجر…',
    addToCart: 'أضف إلى السلة',
    added: 'تمت الإضافة ✓',
    checkout: 'إتمام الطلب',
    continueShopping: 'مواصلة التسوق',
    subscribe: 'اشترك',
    subscribed: 'تم الاشتراك ✓ أهلاً بك',
    selectSize: 'اختر المقاس',
    size: 'المقاس',
    color: 'اللون',
    quantity: 'الكمية',
    viewDetails: 'عرض التفاصيل',
    quickAdd: 'إضافة سريعة',
    newDrop: 'جديد المتجر',
    allItems: 'كل المنتجات',
    featured: 'مميز',
    newest: 'الأحدث',
    lowToHigh: 'السعر: تصاعدياً',
    highToLow: 'السعر: تنازلياً',
    resetFilters: 'مسح الفلاتر',
    clear: 'مسح',
    apply: 'تطبيق',
    save: 'حفظ',
    signOut: 'تسجيل الخروج',
    cart: 'سلة التسوق',
    emptyCart: 'سلتك فارغة',
    subtotal: 'المجموع الفرعي',
    shipping: 'الشحن',
    total: 'المجموع',
    free: 'مجاني',
    remove: 'حذف',
    itemsFound: 'منتجات متوفرة',
    orderSummary: 'ملخص الطلب',
    delivery: 'التوصيل',
    payment: 'الدفع',
    totalToPay: 'المبلغ الإجمالي',
    firstName: 'الاسم الأول',
    lastName: 'النسب',
    fullName: 'الاسم الكامل',
    email: 'البريد الإلكتروني',
    phone: 'الهاتف',
    address: 'العنوان',
    addressLine1: 'العنوان - السطر الأول',
    addressLine2: 'العنوان - السطر الثاني (اختياري)',
    city: 'المدينة',
    postalCode: 'الرمز البريدي',
    country: 'الدولة',
    note: 'ملاحظات (اختياري)',
    createAccount: 'إنشاء حساب (اختياري)',
    password: 'كلمة المرور',
    saveAddress: 'حفظ العنوان',
    passwordHint: 'اتركه فارغاً للطلب كضيف',
    pendingPayment: 'في انتظار التحويل',
    pendingConfirmation: 'تأكيد الاستلام',
    processing: 'قيد التحضير',
    shipped: 'تم الشحن',
    delivered: 'تم التوصيل',
    canceled: 'ملغي',
    orderPlaced: 'تم تسجيل طلبك',
    orderNumber: 'رقم الطلب',
    bankDetails: 'التحويل البنكي',
    transferToAccount: 'يرجى التحويل إلى حسابنا أدناه',
    accountHolder: 'صاحب الحساب',
    rib: 'RIB',
    reference: 'سبب التحويل',
    required: 'مطلوب',
    mandatory: 'إلزامي',
    whatsappProof: 'أرسل الإثبات عبر واتساب',
    viewInAccount: 'عرض في حسابي',
    outOfStock: 'نفذت الكمية',
    myAccount: 'حسابي',
    orders: 'طلباتي',
    profile: 'عنواني ومعلوماتي',
    addressSaved: 'تم تحديث العنوان',
    saveError: 'تعذر الحفظ',
    noOrders: 'لا توجد طلبات بعد',
    viewCatalog: 'ابدأ التسوق',
    orderNo: 'طلب',
    itemsOrdered: 'المنتجات المطلوبة',
    deliveryAddress: 'عنوان التوصيل',
    defaultAddress: 'العنوان الافتراضي',
    transferOf: 'يرجى التحويل بمبلغ',
    loading: 'جاري التحميل…',
    freeShipping: 'شحن مجاني',
    freeShippingOn: 'للطلبات فوق 500 درهم',
    returns: 'إرجاع سهل',
    returnsPolicy: 'خلال 14 يوماً',
    ecoPackaging: 'تغليف بيئي',
    ecoDetails: 'معاد تدويره',
    securePayment: 'تحويل آمن',
    secureDetails: 'تشفير بنكي',
    curatedCollections: 'تشكيلات مختارة',
    shopByCategory: 'تسوق حسب الفئة',
    outerwear: 'الملابس الخارجية',
    essentials: 'الأساسيات اليومية',
    streetwear: 'ستريت وير',
    piecesLimited: 'قطع محدودة',
    subscribeStudio: 'انضم للأستوديو',
    subscribeText: 'الجديد والعروض والوصول المبكر.',
    back: 'رجوع',
    returnToStore: 'العودة للمتجر',
    loadingProduct: 'جاري تحميل المنتج…',
    outOfStockBadge: 'نفذ',
    mandatoryFields: 'يرجى تعبئة الحقول الإلزامية',
    continue: 'متابعة',
    contactTitle: 'تواصل معنا',
    contactSubtitle: 'أسئلة أو تعاونات أو طلبات — نرد بسرعة.',
    contactFormEmail: 'بريدك الإلكتروني',
    contactFormMessage: 'رسالتك',
    contactSend: 'إرسال',
    loginTitle: 'مرحباً بك',
    loginSubtitle: 'سجل الدخول لمتابعة طلباتك.',
    loginWith: 'تسجيل الدخول بالبريد',
    orRegister: 'أو أنشئ حساباً',
    forgot: 'نسيت كلمة المرور',
    newCustomer: 'جديد على ZYN ؟',
    createAccountCTA: 'إنشاء حساب',
    haveAccount: 'لديك حساب بالفعل؟',
    registerHere: 'سجل هنا',
    requiredField: 'يرجى تعبئة هذا الحقل',
    errorAddress: 'يرجى إدخال العنوان والمدينة',
    errorContact: 'يرجى تعبئة معلومات الاتصال',
    errorEmptyCart: 'سلتك فارغة',
    errorSubmit: 'حصل خطأ — يرجى المحاولة مجدداً',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window === 'undefined') return 'en';
    const savedLang = localStorage.getItem('zyn_lang') as Language;
    if (savedLang && ['en', 'fr', 'ar'].includes(savedLang)) {
      return savedLang;
    }
    return 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('zyn_lang', lang);
    if (typeof document !== 'undefined') {
      document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
      document.documentElement.lang = lang;
    }
  };

  useEffect(() => {
    if (typeof document !== 'undefined') {
      document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
      document.documentElement.lang = language;
    }
  }, [language]);

  const t = (key: string) => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  const isRTL = language === 'ar';

  return (
    <LanguageContext.Provider
      value={{
        language,
        locale: language,
        setLanguage,
        setLocale: setLanguage,
        t,
        isRTL,
      }}
    >
      <div dir={isRTL ? 'rtl' : 'ltr'}>{children}</div>
    </LanguageContext.Provider>
  );
}

export const IntlProvider = LanguageProvider;
export default LanguageProvider;

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

export const useTranslation = useLanguage;